from . import res_company
from . import res_config_settings
from . import weighing_mixin
from . import product
from . import sale_order
from . import stock_move_line
from . import stock_move
from . import stock_picking_type
from . import stock_picking
from . import sale_order_line
from . import purchase_order_line
from . import product_pricelist
from . import account_move_line
